[main]
# The default PPD profile
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
# PPD = TuneD
power-saver=cachyos-powersave
balanced=cachyos-desktop
performance=cachyos-gaming

[battery]
# PPD = TuneD
balanced=cachyos-laptop
