#
# tuned configuration
#

[main]
summary=CachyOS balanced battery profile
include=cachyos-common

[cpu]
governor=schedutil|ondemand|powersave
energy_perf_bias=normal
energy_performance_preference=balance_power
boost=1

[acpi]
platform_profile=balanced

[audio]
timeout=10

[video]
radeon_powersave=dpm-balanced, auto
panel_power_savings=1

[usb]
autosuspend=1

[amd_x3d]
mode=frequency
